-- ============================================================================
-- FILE: 03_customer_analysis.sql
-- PURPOSE: Analyze customer behavior and identify top customers
-- AUTHOR: yusufehtesham29
-- ============================================================================

-- Query 1: Top 10 Customers by Sales
-- Identify the most valuable customers (VIPs)
SELECT 
    customer_id,
    customer_name,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(AVG(sales), 2) AS avg_order_value,
    SUM(quantity) AS total_items_purchased
FROM superstore
GROUP BY customer_id, customer_name
ORDER BY total_sales DESC
LIMIT 10;

-- EXPLANATION:
-- Groups all transactions by each customer
-- SUM(sales): Total revenue generated by each customer
-- COUNT(DISTINCT order_id): How many times they've ordered
-- AVG(sales): Average spend per order
-- LIMIT 10: Shows only the top 10 customers
-- These are your VIP customers - prioritize retention strategies for them
-- ============================================================================


-- Query 2: Top 10 Customers by Profit
-- Identify most profitable customers (may differ from highest sales)
SELECT 
    customer_id,
    customer_name,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(SUM(profit) / SUM(sales) * 100, 2) AS profit_margin_percent
FROM superstore
GROUP BY customer_id, customer_name
ORDER BY total_profit DESC
LIMIT 10;

-- EXPLANATION:
-- Focus on profit instead of just revenue
-- Some customers may buy a lot but with high discounts (low profit)
-- Others may buy less but at full price (higher profit margin)
-- This helps identify truly valuable customers
-- ============================================================================


-- Query 3: Customer Segmentation Analysis
-- Analyze performance by customer segment (Consumer, Corporate, Home Office)
SELECT 
    segment,
    COUNT(DISTINCT customer_id) AS total_customers,
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(AVG(sales), 2) AS avg_order_value,
    ROUND(SUM(profit) / SUM(sales) * 100, 2) AS profit_margin_percent
FROM superstore
GROUP BY segment
ORDER BY total_sales DESC;

-- EXPLANATION:
-- Customer segments represent different business types
-- Consumer: Individual buyers
-- Corporate: Business/company purchases
-- Home Office: Small business/home-based businesses
-- Shows which segment is most valuable to the business
-- ============================================================================


-- Query 4: Customer Purchase Frequency Distribution
-- Understand how often customers buy
SELECT 
    orders_placed,
    COUNT(*) AS number_of_customers,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS percentage_of_customers
FROM (
    SELECT 
        customer_id,
        COUNT(DISTINCT order_id) AS orders_placed
    FROM superstore
    GROUP BY customer_id
)
GROUP BY orders_placed
ORDER BY orders_placed DESC;

-- EXPLANATION:
-- Inner query: Counts how many orders each customer has placed
-- Outer query: Groups customers by order frequency
-- Shows distribution: How many customers ordered 1 time, 2 times, etc.
-- OVER(): Window function to calculate percentage of total customers
-- Helps identify one-time vs. repeat customers
-- ============================================================================
